# Generated by Django 4.1.1 on 2022-10-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0002_alter_groupp_academ_sov_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='kol_stud_budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол. студ.бюджет'),
        ),
    ]
