# Generated by Django 4.1.1 on 2022-10-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0004_alter_groupp_academ_sov_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='amount_of_hour',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='discipline_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nagr.discipline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='group_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='nagr.groupp'),
            preserve_default=False,
        ),
    ]
