# Generated by Django 4.1.1 on 2022-10-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0005_remove_discipline_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='discipline_id',
        ),
        migrations.AddField(
            model_name='discipline',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nagr.teacher'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='group_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='group_id',
            field=models.ManyToManyField(to='nagr.groupp'),
        ),
    ]
