# Generated by Django 4.1.1 on 2022-10-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0006_remove_teacher_discipline_id_discipline_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='amount_of_hour',
        ),
        migrations.AddField(
            model_name='discipline',
            name='amount_of_hour',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discipline',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplene', to='nagr.teacher'),
        ),
    ]
