# Generated by Django 4.1.1 on 2022-10-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0007_remove_teacher_amount_of_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='group_id',
        ),
        migrations.AddField(
            model_name='discipline',
            name='group_id',
            field=models.ManyToManyField(to='nagr.groupp'),
        ),
    ]
