# Generated by Django 4.1.1 on 2022-10-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0008_remove_teacher_group_id_discipline_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='amount_of_credit',
        ),
        migrations.AddField(
            model_name='groupp',
            name='amount_of_credit',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
