# Generated by Django 4.1.1 on 2022-10-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0009_remove_discipline_amount_of_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='amount_of_credit',
            field=models.IntegerField(default=5),
        ),
    ]
