# Generated by Django 4.1.1 on 2022-10-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0011_alter_groupp_priem_srs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='kontrol_tekuchiy3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Контроль/текущий (3 контр.точка)'),
        ),
    ]
