# Generated by Django 4.1.1 on 2022-10-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0012_alter_groupp_kontrol_tekuchiy3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='kontrol_tekuchiy1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Контроль/текущий (1 контр.точка)'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='kontrol_tekuchiy2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Контроль/текущий (2 контр.точка)'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='praktika_nauchno',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Практика/Научно-исследовательская'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='praktika_pedagog',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Практика/Педагогическая'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='praktika_predkval',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Практика/Предквал'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='praktika_proizvod',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Практика/Производ'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='praktika_uchebnay',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Практика/Учебная'),
        ),
    ]
