# Generated by Django 4.1.1 on 2022-10-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0013_alter_groupp_kontrol_tekuchiy1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='kontrol_tekuchiy1',
            field=models.FloatField(blank=True, null=True, verbose_name='Контроль/текущий (1 контр.точка)'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='kontrol_tekuchiy2',
            field=models.FloatField(blank=True, null=True, verbose_name='Контроль/текущий (2 контр.точка)'),
        ),
    ]
