# Generated by Django 4.1.1 on 2022-10-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0014_alter_groupp_kontrol_tekuchiy1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='praktika_nauchno',
            field=models.IntegerField(blank=True, null=True, verbose_name='Практика/Научно-исследовательская'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='praktika_pedagog',
            field=models.IntegerField(blank=True, null=True, verbose_name='Практика/Педагогическая'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='praktika_predkval',
            field=models.IntegerField(blank=True, null=True, verbose_name='Практика/Предквал'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='praktika_proizvod',
            field=models.IntegerField(blank=True, null=True, verbose_name='Практика/Производ'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='praktika_uchebnay',
            field=models.IntegerField(blank=True, null=True, verbose_name='Практика/Учебная'),
        ),
    ]
