# Generated by Django 4.1.1 on 2022-10-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0016_alter_groupp_priem_srs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='priem_SRS',
            field=models.FloatField(blank=True, null=True, verbose_name='Прием СРС'),
        ),
    ]
