# Generated by Django 4.1.1 on 2022-10-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0019_alter_groupp_academ_sov_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='amount_of_hour',
        ),
    ]
