# Generated by Django 4.1.1 on 2022-10-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0020_remove_discipline_amount_of_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupp',
            name='teacher',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='nagr.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discipline',
            name='group_id',
            field=models.ManyToManyField(related_name='group', to='nagr.groupp'),
        ),
    ]
