# Generated by Django 4.1.1 on 2022-10-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0021_groupp_teacher_alter_discipline_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summ', to='nagr.teacher'),
        ),
    ]
